### ISSUE TITLE
Issue 01: (CreateScene)

### ISSUE THREAD

**Issue by Manfreack** [El-Matyzz/Scene-Manager#1]
Al crear una escena nueva salta un error:
 ![2017-10-31](https://user-images.githubusercontent.com/32555736/32246878-2f454076-be5f-11e7-8700-4aaa464a62de.png)
Se menciona que se está ejecutando una **_operación inválida_**. A pesar de este error, el botón funciona a la perfección, por lo que este error no limita la funcionalidad del mismo.

P.D: Poner _Repaint()_ tras la función no soluciona el problema.

**Comment by inakilasaigues** [comment]
En Scene_Manager_Editor.cs, linea 181, abren un grupo vertical que no cierran nunca. De hecho, abren cinco horizontales y un vertical, pero hacen seis endHorizontal

**Comment by Manfreack** [comment]
Oh, genial, voy a probar de arreglarlo mañana. Gracias!
